---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authentik-charts.yaml
  - bitnami-charts.yaml
  - coredns-charts.yaml
  - deliveryhero-charts.yaml
  - emberstack-charts.yaml
  - external-dns-charts.yaml
  - fairwinds-charts.yaml
  - grafana-charts.yaml
  - grafana-loki-charts.yaml
  - hajimari-charts.yaml
  - infracloudio-charts.yaml
  - jetstack-charts.yaml
  - k8s-at-home-charts.yaml
  - k8s-gateway-charts.yaml
  - kasten-charts.yaml
  - kpg-charts.yaml
  - descheduler-charts.yaml
  - lwolf-charts.yaml
  - metrics-server-charts.yaml
  - node-feature-discovery-charts.yaml
  - reflector-charts.yaml
  - rook-ceph-charts.yaml
  - stakater-charts.yaml
  - traefik-charts.yaml
  - weaveworks-kured-charts.yaml
