---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #â€š- calico-system
  #- cert-manager
  - flux-system
  #- home
  #- home-automation
  #- kube-system
  #- media
  #- monitoring
  - network
  #- system-upgrade
