---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - calico-system
  - cert-manager
  - flux-system
  - home
  - home-automation
  - kube-tools
  - kyverno
  - media
  - monitoring
  - networking
  - rook-ceph
  - storage
  - system-upgrade
