---
collections:
  - name: ansible.posix
    version: 1.3.0
  - name: community.general
    version: 5.0.0
  - name: community.docker
    version: 2.5.1
  - name: community.kubernetes
    version: 2.0.1
  - name: community.sops
    version: 1.2.1

roles:
  - src: xanmanning.k3s
    version: v3.1.2
  - src: geerlingguy.pip
    version: 2.1.0
  - src: geerlingguy.docker
    version: 4.1.1