#ENC[AES256_GCM,data:00SfdvJlSJRz0j4FPz31kNg=,iv:qkXvvFB/Ypt2MRC0KCxchiUh5yHWzZewVgV3xrMKXyw=,tag:rxeWnXR9DfLHQ36CPrl25w==,type:comment]
ansible_become_pass: ENC[AES256_GCM,data:pNzEeK+Gd2aM,iv:fHv6RyEfXNCLFoG7hxXU5avbnL+hl3u13++GHVB9qvA=,tag:aMDffK2t6XHRvadf0CaruA==,type:str]
SECRET_DOMAIN: ENC[AES256_GCM,data:U+TtyE/IMh1zk3w=,iv:bV+g+/ge3Xvqd//LxPjTLDrXfPvjyVfN+Rmv82Iv47c=,tag:l7p9tUDLsCuJifrLYjT9Kg==,type:str]
SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Q8e1LJNiHYJ1utEj2w==,iv:MXCBkL/SfJSkMxZZYJgejenSib8qjsWLRHspV49g+bs=,tag:2WH5LFSSY6ntZB40RGzqxw==,type:str]
SECRET_CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:MSxbVPlm+N4oPYADvIwAym/vcMwqZUq6jDeqd+cVFvSg5gvkFg==,iv:XZ2eN4Ho2+eoHd2H8Th7AgDqK9/6Gm4u0FaOLztHtw4=,tag:aoaOrpWHI+laZ4KXoFQ/kQ==,type:str]
SECRET_MINIO_ROOT_USER: ENC[AES256_GCM,data:C9HEZdk=,iv:dmXBEVjvccbvA+PgEWI00T+xEePQqLVHWpKc+8yL5WA=,tag:n7FycjQMlEBfNKZtgx4krw==,type:str]
SECRET_MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:MLjdBwaypgTz,iv:T2qkSsbagvZOCVp2zFAb9nN2C+D2x8xOVzH3fNxKCBc=,tag:jHs8wI5ACZ03ZcWB7xlR+A==,type:str]
SECRET_POSTGRESQL_USERNAME: ENC[AES256_GCM,data:IKSdU+k=,iv:6B9ivuaPSjBE+t2lgQnTn1I18CRZvNCZ6xUf6JaMnso=,tag:Y57l5VkWaxDiQXUZ+1kMNw==,type:str]
SECRET_POSTGRESQL_PASSWORD: ENC[AES256_GCM,data:OaGlS5mJutxT,iv:udLvO4LB9p7pYHuM67jdalu+aKm3fiUSmg908zUUzEo=,tag:jO9ewEntyFFjgpj1nKP/Sg==,type:str]
SECRET_PGADMIN_USERNAME: ENC[AES256_GCM,data:eUtBnpuyP7t0owBlLA==,iv:JOHNMFRkvGGUVUkWHQ+JhKJddqo/zj8dNjdNEcx96Kk=,tag:MwCUznziPte0rmm/IhGkBg==,type:str]
SECRET_PGADMIN_PASSWORD: ENC[AES256_GCM,data:hTvtY0kQR72B,iv:f8attwgvrKxNmP0bpDHlw/PKzUFvIZh9L0QulTCd1VI=,tag:gwUpbIVzndu561PZLhnyzw==,type:str]
SECRET_MARIADB_PASSWORD: ENC[AES256_GCM,data:Engm2kkQ2U70,iv:fEowoh00eVArah6mGmVdTuT1xVrOQmrHOZfZGAfwu0c=,tag:QFk0+AanBoN1cI1Tc7CNsg==,type:str]
SECRET_B2_APPLICATION_KEY_ID: ENC[AES256_GCM,data:heAHzIWgpzeqhG2/3R9Q23LFXe+zQnRo3A==,iv:14l5K0lrhttn+j1od/9fuhUmkKARQIC/ST1Qvr3V6Y0=,tag:SyvzeB5s4Pf6LP+w8BW6oQ==,type:str]
SECRET_B2_APPLICATION_KEY: ENC[AES256_GCM,data:a51s97y+A06g6YEVtgfoKoQO3W9qqAGF4MdVqwc2Wg==,iv:ZpVD5xV5jAJ8AHI3CT1xNc1hQtloQUVi7qW+szVe5is=,tag:iX9ze7llbJHst682uCvKzw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kmnhp30e40u4q54znn8ysz3atvee5k4q9r585y8mzxz9xuuxm37spk5w4w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UnZ3U1NHU2NvbE50QnNa
            OFJ3M0w0dUxwVEpoWFByNXFPU21KNUdPY0J3ClhLQjV1aEZKcjArdjgwSXkxbitS
            NitNWXBqOU5vaEVkanFsanI1ZWcrbHcKLS0tIHlIM3NaYVA2a2ZMZWdQQkNsRnJo
            d0JqcmJGMWpsRmF6NkNyQ3pMU3hmVncK5xuG7zPNxHvCDGAwOBdMOyW0hxZsiPMe
            f8qsIfbVOLowoJ9ODO+FMkXS6ZJ5EhKYMlZ7fUXePCJ4gGYKGrN4sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-06T15:30:51Z"
    mac: ENC[AES256_GCM,data:FXrwP0YlMk3MZWFI5Ot3+tvc8pDiCjZVw/66XJ2AA9GQxYa8gPw1cpCUkDa4Okg3dCE72LdxRgV2mhA7QrWtnj+SzB7hcjuNsSspGC3mF0JVJTJ0qgogaWL4cn/YkrgCMCE7BFU0PflXJ1EqZitUAd+CWsvOk+sx5WWUzi69kmo=,iv:3lD0ffK6s8onNvVWReZKhoiOLnNjYTJGhi5QfHDREKE=,tag:8ThxMQ7Mm0WyS22TtHNLOw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
