---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - calico-system.yaml
  - cert-manager.yaml
  - home-automation.yaml
  - network.yaml
  - home.yaml
  - kasten-io.yaml
  - media.yaml
  - monitoring.yaml
  - rook-ceph.yaml
